version: '3'

services:
  client:
    build: 
      context: ./Interface/iot-interface
    networks:
      - iot-network
    ports:
      - "3000:3000"

  broker:
    build: 
      context: ./Broker
    networks:
      - iot-network
    ports:
      - "8080:8080"
      - "5000:5000/udp"

  server:
    build: 
      context: ./Server
    networks:
      - iot-network
    ports:
      - "3002:3002"
    environment:
      - BROKER_IP=<IP REAL DO BROKER>
      - DEVICE_NAME=<NOME DO DISPOSITIVO>

networks:
  iot-network:
    driver: bridge